packages/org.json_schema.contrib/PklProject, packages/org.json_schema.contrib/internal/ModuleGenerator.pkl, packages/org.json_schema.contrib/tests/ModuleGenerator.pkl, packages/org.json_schema.contrib/tests/ModuleGenerator.pkl-expected.pcf
This PR fixes a bug that leads to the generation of duplicated codes when multiple JSON schema definitions share the same property name. As a result, the code generation process produces multiple classes whit the same name.
=> Fix duplicated class names

packages/org.json_schema.contrib/PklProject, packages/org.json_schema.contrib/internal/ModuleGenerator.pkl, packages/pkl.experimental.syntax/ExpressionNode.pkl, packages/pkl.experimental.syntax/ModuleNode.pkl, packages/pkl.experimental.syntax/PklProject, packages/pkl.experimental.syntax/TypeNode.pkl
These are vestiges from old Pkl when this actually mattered.
=> Remove unnecessary `= Undefined()`

packages/k8s.contrib.crd/PklProject, packages/k8s.contrib.crd/PklProject.deps.json, packages/pkl.experimental.deepToTyped/PklProject, packages/pkl.experimental.deepToTyped/deepToTyped.pkl, packages/pkl.experimental.deepToTyped/tests/deepToTyped.pkl
Bump versions, and change k8s.contrib.crd to depend on local package.
Closes #25
=> [pkl.experimental.deepToTyped] Support types containing Any

packages/com.circleci.v2/Config.pkl, packages/com.circleci.v2/PklProject
In version 2.1 of the CircleCI configuration you can specify top-level executors to support sharing data between jobs. I didn't see this present in the pkl template, so this PR adds that.
=> [CircleCI] Add support for top-level executors

.circleci/config.pkl, .circleci/config.yml
Also: this makes our PRB build job not depend on `pr-approval/authenticate`.
=> Switch to PklCI from commons repo

build.gradle.kts
The `exec {}` blocks were still running despite `enabled` being set to false.
=> Prevent Gradle from modifying git config locally

packages/pkl.experimental.net/PklProject, packages/pkl.experimental.net/net.pkl, packages/pkl.experimental.net/tests/net.pkl
This PR introduces a test suite for IP address strings, complete with failing tests for IP address strings containing unicode digits, and then fixes the failing tests by changing the regexes to stop allowing unicode digits.
As part of this work I also converted the IPv6 regex into expanded form with whitespaces and comments in order to make it more readable so I could verify the test suite covered everything. The new regex is identical to the old one so no behavior changed there. That commit could be removed without changing the rest of this PR but it seems nice to have.
=> [pkl.experimental.net] Disallow unicode digits in IPs, ports

packages/org.openapis.v3.contrib/PklProject, packages/org.openapis.v3.contrib/SchemaGenerator.pkl
Generating an empty `required` list is a spec violation.
=> [org.openapis.v3.contrib] Omit `required` when no fields are actually required.

packages/org.openapis.v3.contrib/PklProject, packages/org.openapis.v3.contrib/PklProject.deps.json, packages/org.openapis.v3/Operation.pkl, packages/org.openapis.v3/PklProject
Example of usage:
```pkl
paths {
["/books"] {
get {
responses {
[HTTPResponse.OK] = new Reference { `$ref` = "#/components/responses/200GetBooks" }
}
}
}
}
```
=> [org.openapis.v3] Allow using Reference as OpenApi response value

packages/io.prometheus/PklProject, packages/io.prometheus/Rule.pkl
The current RuleGroup specs are missing some fields from Prometheus Operartor's API: https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.RuleGroup
=> [io.prometheus] Update Prometheus RuleGroup specs

packages/k8s.contrib.crd/PklProject, packages/k8s.contrib.crd/PklProject.deps.json, packages/k8s.contrib.crd/generate.pkl, packages/k8s.contrib/PklProject, packages/k8s.contrib/PklProject.deps.json, packages/k8s.contrib/convert.pkl, packages/org.json_schema.contrib/PklProject, packages/org.json_schema.contrib/generate.pkl, packages/pkl.pipe/PklProject, packages/pkl.pipe/PklProject.deps.json
This makes various "scripts" that read off PWD as compatible on Windows.
Also: fixes issues where a relative path may contain spaces.
=> Make conversion scripts compatible on Windows

packages/k8s.contrib.crd/PklProject, packages/k8s.contrib.crd/PklProject.deps.json, packages/org.json_schema.contrib/PklProject, packages/org.json_schema.contrib/PklProject.deps.json, packages/pkl.experimental.syntax/PklProject, packages/pkl.experimental.syntax/TypeAliasNode.pkl, packages/pkl.experimental.syntax/tests/ExpressionNode.pkl-expected.pcf, packages/pkl.experimental.syntax/tests/ModuleNode.pkl, packages/pkl.experimental.syntax/tests/ModuleNode.pkl-expected.pcf
There's some extraneous diff in `packages/pkl.experimental.syntax/tests/ExpressionNode.pkl-expected.pcf` because I ran `pkl test --overwrite` and it subbed in raw strings where there were plain strings with escapes previously. I figure this is probably desirable overall, but I'd be happy to revert it based on feedback.
=> [pkl.experimental.syntax] Do not generate spaces at EOL for long typealiases

packages/com.influxdata.telegraf/PklProject, packages/com.influxdata.telegraf/PklProject.deps.json, packages/pkl.toml/PklProject, packages/pkl.toml/examples/basic.pkl, packages/pkl.toml/tests/toml.pkl-expected.pcf, packages/pkl.toml/toml.pkl
Extended the test case with an empty `Mapping` value, which did not produce a table heading in the previous version although it should.
pkl should eval an empty `Map` to an output that contains the TOML table header without further values.
The previous version explicitly skipped rendering the header assuming there were deeper tables that would follow, however that is not the case with an empty `Map`
=> Bugfix: support empty Mapping in TOML output

packages/k8s.contrib.crd/PklProject, packages/k8s.contrib.crd/PklProject.deps.json, packages/pkl.experimental.deepToTyped/PklProject, packages/pkl.experimental.deepToTyped/deepToTyped.pkl, packages/pkl.experimental.structuredRead/PklProject, packages/pkl.experimental.structuredRead/PklProject.deps.json
Sometimes you want to be able to collect multiple conversion errors from multiple deepToTyped.apply calls, this change makes that possible.
=> Add an attemptApply function to deepToTyped

packages/k8s.contrib.crd/PklProject, packages/k8s.contrib.crd/PklProject.deps.json, packages/pkl.experimental.deepToTyped/PklProject, packages/pkl.experimental.deepToTyped/deepToTyped.pkl, packages/pkl.experimental.structuredRead/PklProject, packages/pkl.experimental.structuredRead/PklProject.deps.json
The conversion failure class needs to be exposed if people are going to interpret the result of attemptApply.
=> Expose the conversion failure class

packages/com.circleci.v2/Config.pkl, packages/com.circleci.v2/PklProject
According to CircleCI documentation, `docker_layer_caching` must be correct spelling of the parameter.
> docker_layer_caching | N | boolean | Set this to true to enable Docker Layer Caching in the Remote Docker Environment (default: false)
> Set this to true to enable [Docker Layer Caching](https://circleci.com/docs/docker-layer-caching/) in the Remote Docker Environment (default: false)
https://circleci.com/docs/configuration-reference/#setupremotedocker
=> Fix typo in CircleCI's `setup_remote_docker` parameter; s/docker_layer_cacheing/docker_layer_caching/

packages/com.circleci.v2/Config.pkl, packages/com.circleci.v2/PklProject
According to CircleCI documentation on [setup_remote_docker](https://circleci.com/docs/configuration-reference/#setupremotedocker), both `version` and `docker_layer_caching` are NOT required one.
Key | Required | Type | Description
-- | -- | -- | --
docker_layer_caching | N | boolean | Set this to true to enable Docker Layer Caching in the Remote Docker Environment (default: false)
version | N | String | Version string of Docker you would like to use (default: 24.0.9). View the list of supported Docker versions here.
cf. https://circleci.com/docs/configuration-reference/#setupremotedocker
=> [com.circleci.v2] Make `setup_remote_docker` parameters as optional

packages/com.circleci.v2/Config.pkl, packages/com.circleci.v2/PklProject
Just as similar as pipeline parameters (toplevel), CircleCI also supports `parameters` at job-level (cf. https://circleci.com/docs/configuration-reference/#parameters-job). The parameter syntax is [identical to the pipeline parameters](https://circleci.com/docs/reusing-config/#parameter-syntax).
Job-level parameters are useful especially when I'm configuring [matrix builds](https://circleci.com/docs/configuration-reference/#matrix). I'd like this to be supported :pray:
=> [com.circleci.v2] Support job-level parameters

packages/com.circleci.v2/Config.pkl, packages/com.circleci.v2/PklProject, packages/com.circleci.v2/examples/build_and_push_image_w_registry_login.pkl, packages/com.circleci.v2/tests/Config.pkl-expected.pcf
By default CircleCI workflow jobs can take parameters like `name`, `context`, `type`, `filters`, etc. Along with these default parameters, it is not very explicitly described on [CircleCI's configuration reference](https://circleci.com/docs/configuration-reference/#job-name-in-workflow), however, it also can take custom job-level parameters defined by users.
So far there was no way to specify these custom parameters while calling a workflow job. This allows user to specify custom `parameters` while invoking a WorkflowJob.
---
Here's some references of usage of job-level custom parameters. JFYI
https://github.com/CircleCI-Public/aws-ecr-orb/blob/v9.3.7/src/examples/build_and_push_image_w_registry_login.yml#L21-L36
https://github.com/CircleCI-Public/aws-ecr-orb/blob/v9.3.7/src/jobs/build_and …
=> [com.circleci.v2] Support specifying custom job-level parameters while calling a job in a workflow

packages/com.circleci.v2/Config.pkl, packages/com.circleci.v2/PklProject
Adds support for CircleCI's matrix jobs.
The configuration schema was simple enough to implement it in Pkl as it is.
Key | Required | Type | Description
-- | -- | -- | --
parameters | Y | Map | A map of parameter names to every value the job should be called with
exclude | N | List | A list of argument maps that should be excluded from the matrix
alias | N | String | An alias for the matrix, usable from another job’s requires stanza. Defaults to the name of the job being executed
https://circleci.com/docs/configuration-reference/#matrix
=> [com.circleci.v2] Support CircleCI workflow job matrix

packages/k8s.contrib.crd/PklProject, packages/k8s.contrib.crd/PklProject.deps.json, packages/pkl.experimental.deepToTyped/PklProject, packages/pkl.experimental.deepToTyped/deepToTyped.pkl, packages/pkl.experimental.deepToTyped/tests/deepToTyped.pkl, packages/pkl.experimental.structuredRead/PklProject, packages/pkl.experimental.structuredRead/PklProject.deps.json
Sometimes a complex, nested Pkl class/module must be "unmarshalled" from a serialized format like JSON or YAML. `pkl.experimental.deepToTyped` is the low-boilerplate tool of choice for such transformations. Occasionally, the names of properties in the input data do not match the property names of Pkl types, for example Pkl typically uses `camelCase` while JSON can use `snake_case` or `kebab-case`. `deepToTyped` cannot currently handle this task.
This PR introduces a new customization point in the `deepToTyped` module: the `keyTransform` property can be set to a function mapping a `reflect.Property` to the `String` name that should be used to find the property's value in the input instead of its name. If this function returns `null`, the property's original name is used.
=> [pkl.experimental.deepToTyped] Add support for key transformations during apply

packages/org.openapis.v3.contrib/PklProject, packages/org.openapis.v3.contrib/PklProject.deps.json, packages/org.openapis.v3/PklProject, packages/org.openapis.v3/SecurityScheme.pkl
This pull request addresses the issue of being able to make a correctly configured security scheme for HTTP security schemes like Bearer Auth Tokens.
For more information, see the original issue: #90
=> [org.openapis.v3] Security Scheme Update for HTTP/Bearer Auth

packages/k8s.contrib.crd/PklProject, packages/k8s.contrib.crd/PklProject.deps.json, packages/k8s.contrib.crd/internal/ModuleGenerator.pkl, packages/org.json_schema.contrib/PklProject, packages/org.json_schema.contrib/internal/ModuleGenerator.pkl, packages/org.json_schema.contrib/tests/ModuleGenerator.pkl, packages/org.json_schema.contrib/tests/ModuleGenerator.pkl-expected.pcf
For example, handles if a class name would otherwise be generated as `Mapping`.
This instead turns it into `Mapping1`.
=> Fix name conflicts in k8s CRD and JSON schema generators

packages/com.circleci.v2/Config.pkl, packages/com.circleci.v2/PklProject
Bumped version to 1.5.0.
See: https://circleci.com/docs/configuration-reference/#macos-execution-environment
=> Add support for `m2pro` (medium, large) resource classes

packages/k8s.contrib.crd/PklProject, packages/k8s.contrib.crd/PklProject.deps.json, packages/k8s.contrib.crd/generate.pkl, packages/k8s.contrib.crd/internal/ModuleGenerator.pkl, packages/k8s.contrib.crd/tests/ModuleGenerator.pkl-expected.pcf
Currently, the generator only generates the stored version. This changes the behvaior to generate for every other version.
As part of this change, the output path includes the version. For example, the output might produce the following:
* v1beta1/MyResource.pkl
* v1beta2/MyResource.pkl
Also: Bump k8s version to 1.2.0
=> [k8s.contrib.crd] Generate CRDs for every version

packages/icalendar/PklProject, packages/icalendar/PklProject.deps.json, packages/icalendar/tests/Recur.pkl, packages/icalendar/type/Date.pkl, packages/icalendar/type/DateTime.pkl, packages/icalendar/type/Recur.pkl, packages/icalendar/type/Time.pkl
This PR introduces functionality for handling [RFC 5545 Recurrence Rules](https://datatracker.ietf.org/doc/html/rfc5545#autoid-42).
In general, attempts are made to conform strictly to the RFC where possible, but there are some small deviations.
Included functionality:
* Modules representing the `DATE`, `DATE-TIME`, `RECUR`, and `TIME` property value data types
* Rendering of each of these types to their serialized form via `toString()`
* Parsing of `Date`, `DateTime`, and `Time` objects from their string representations
Omitted functionality that can be added in the future:
* Parsing of `Recur` objects from their string representations
* Support for other structured property value data types
* Support for calendar objects or specific calendar components (eg. events, to-dos, alarms, etc.)
=> [icalendar] Add package

packages/k8s.contrib.crd/PklProject, packages/k8s.contrib.crd/PklProject.deps.json, packages/pkl.experimental.deepToTyped/PklProject, packages/pkl.experimental.deepToTyped/deepToTyped.pkl, packages/pkl.experimental.structuredRead/PklProject, packages/pkl.experimental.structuredRead/PklProject.deps.json
When a conversion failure occurs deepToTyped creates a path to the location of the failure in the object that's undergoing conversion. Now the error indicates both the type and location of the error making it much easier to debug problems.
Example of previous error:
```
Expected "String" but got "Dynamic"
```
Example of new error:
```
Expected "String" but got "Dynamic" at 
.metadata.managedFields[0].fieldsV1
```
=> Improve error message provided on conversion failure

packages/io.prometheus/PklProject, packages/io.prometheus/Rule.pkl, packages/io.prometheus/examples/rule.pkl, packages/io.prometheus/tests/rule.pkl-expected.pcf
Prometheus has added the labels field to alerting and recording rule groups and it's quite useful.
See https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#rule_group
=> Add labels field to Prometheus rule groups

packages/k8s.contrib.crd/PklProject, packages/k8s.contrib.crd/generate.pkl, packages/k8s.contrib.crd/internal/SchemaGenerator.pkl, packages/k8s.contrib.crd/tests/ModuleGenerator.pkl, packages/k8s.contrib.crd/tests/ModuleGenerator.pkl-expected.pcf, packages/k8s.contrib.crd/tests/SchemaGenerator.pkl, packages/k8s.contrib.crd/tests/SchemaGenerator.pkl-expected.pcf, packages/k8s.contrib.crd/tests/fixtures/crds_conflict.yaml, packages/k8s.contrib.crd/tests/fixtures/crds_subdomain.yaml
This PR adds generation of a schema module similar to [the one from pkl-k8s](https://github.com/apple/pkl-k8s/blob/main/generated-package/k8sSchema.pkl), which enables easy import and use in [`k8s.contrib`'s converter module](https://pkl-lang.org/package-docs/pkg.pkl-lang.org/pkl-pantry/k8s.contrib/current/convert/index.html#resourcesToConvert)
=> [k8s.contrib.crd] Add generation of k8sSchema module

packages/com.circleci.v2/Config.pkl, packages/com.circleci.v2/PklProject
`circleci_ip_ranges` is an option available for CircleCI's paid account in Performance or Scale plan.
refs:
* https://circleci.com/docs/reference/configuration-reference/#circleciipranges
* https://circleci.com/docs/guides/security/ip-ranges/
=> [com.circleci.v2] Add support for `circleci_ip_ranges` option in a Job class
